name: 'Release Binary'
on:
  push:
    branches:
      - master
jobs:
  build:
    name: 'Build NIV binary'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2
      - name: 'Install Packaging module'
        run: npm install -g pkg
      - name: 'Create .env file'
        run: |
          cat << EOF > .env
          PORT=3000
          DATABASE_URL=mongodb://localhost/niv
          ACCESS_TOKEN=secretsecretsecret
          FROM_EMAIL=kaustubh.murumkar@gmail.com
          FROM_PWD=ywfrfjtrjfncdfmr
          EMAIL_TOK=secretsecretsecretsecretsecretsecret
          HOST=http://localhost
          NODE_ENV=development
          REDIS_PORT=6379
          REDIS_HOST=localhost
          REDIS=yes
          INSTITUTE=niv
          MASTER_PWD=admin1234
          LOGPATH=logs/
          BACKUPDIR=backup/
          EOF
      - name: 'Run Build'
        run: npm run pkg
      - name: 'Upload Binary artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: niv
          path: ./niv
  release:
    name: 'Create GitHub Release'
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Download Binary Artifacts'
        uses: actions/download-artifact@v2
        with:
          name: niv
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./niv
          tag_name: v${{ github.run_number }}
          name: Release V${{ github.run_number }}
